export const deck = [
  // --- Major Arcana ---
  { name: "The Fool", arcana: "Major", interpretation: "A leap of faith awaits. Embrace new beginnings with an open heart and beginner's mind — the journey matters more than the destination." },
  { name: "The Magician", arcana: "Major", interpretation: "You have all the tools you need. Channel your willpower and skill — manifestation is within reach if you act with intention." },
  { name: "The High Priestess", arcana: "Major", interpretation: "Trust your intuition over logic right now. Hidden knowledge is surfacing; sit with the mystery rather than forcing answers." },
  { name: "The Empress", arcana: "Major", interpretation: "Abundance and creativity flow freely. Nurture yourself and others — growth comes through patience and connection to nature." },
  { name: "The Emperor", arcana: "Major", interpretation: "Structure and authority are your allies. Establish order, set clear boundaries, and lead with confidence and discipline." },
  { name: "The Hierophant", arcana: "Major", interpretation: "Tradition and established wisdom offer guidance. Seek counsel from mentors or institutions, or question the conventions that no longer serve you." },
  { name: "The Lovers", arcana: "Major", interpretation: "A meaningful choice stands before you — often about values, not just romance. Alignment of heart and mind leads to the right path." },
  { name: "The Chariot", arcana: "Major", interpretation: "Victory through determination. Harness opposing forces and drive forward with focus — willpower overcomes all obstacles." },
  { name: "Strength", arcana: "Major", interpretation: "True strength is gentle. Courage comes from compassion and inner calm, not force. You have more resilience than you realize." },
  { name: "The Hermit", arcana: "Major", interpretation: "Withdraw to find clarity. A period of solitude and inner reflection reveals the answers you've been seeking from others." },
  { name: "Wheel of Fortune", arcana: "Major", interpretation: "Cycles turn — what goes down must come up. Accept change as the only constant, and recognize the larger forces at play in your life." },
  { name: "Justice", arcana: "Major", interpretation: "Truth and fairness prevail. Cause and effect are in motion; own your actions and seek balance in all decisions." },
  { name: "The Hanged Man", arcana: "Major", interpretation: "Surrender brings perspective. Pause, let go of control, and view the situation from a completely different angle." },
  { name: "Death", arcana: "Major", interpretation: "Not an ending, but a transformation. Release what no longer serves you to make space for powerful new beginnings." },
  { name: "Temperance", arcana: "Major", interpretation: "Balance and moderation are the keys right now. Blend opposing elements with patience — the middle path leads to healing." },
  { name: "The Devil", arcana: "Major", interpretation: "Examine what binds you. Addictions, fears, and unhealthy patterns can be broken — the chains are often of your own making." },
  { name: "The Tower", arcana: "Major", interpretation: "Sudden disruption shatters what was built on shaky ground. Though jarring, this upheaval clears the way for something more authentic." },
  { name: "The Star", arcana: "Major", interpretation: "Hope returns after hardship. Trust the universe's guidance, and allow yourself to be renewed by faith and calm clarity." },
  { name: "The Moon", arcana: "Major", interpretation: "Illusion and anxiety cloud the path. Navigate by feel rather than sight — not everything is as it appears in the dark." },
  { name: "The Sun", arcana: "Major", interpretation: "Joy, clarity, and success shine through. Confidence and vitality are yours — celebrate what is working and share your light." },
  { name: "Judgement", arcana: "Major", interpretation: "A moment of reckoning and awakening. Reflect honestly on your past and heed the call to rise into your true purpose." },
  { name: "The World", arcana: "Major", interpretation: "Completion and wholeness. A cycle has ended in triumph — integrate everything you've learned and step into your next chapter." },

  // --- Minor Arcana: Wands ---
  { name: "Ace of Wands", arcana: "Wands", interpretation: "A spark of inspiration ignites. Creative energy and ambition surge — seize this raw potential before it fades." },
  { name: "Two of Wands", arcana: "Wands", interpretation: "You stand at the threshold of a bold plan. The world is yours to explore — dare to think beyond your current horizon." },
  { name: "Three of Wands", arcana: "Wands", interpretation: "Your efforts are paying off. Expansion is underway; watch for opportunities arriving from a distance." },
  { name: "Four of Wands", arcana: "Wands", interpretation: "Celebrate a milestone. Community, stability, and joy mark this moment of well-earned rest and recognition." },
  { name: "Five of Wands", arcana: "Wands", interpretation: "Conflict and competition heat up. Not all struggle is harmful — channel the friction into productive challenge." },
  { name: "Six of Wands", arcana: "Wands", interpretation: "Public recognition arrives. Your hard work is being seen; carry success with confidence, not arrogance." },
  { name: "Seven of Wands", arcana: "Wands", interpretation: "Hold your ground. You're being challenged from multiple sides — defend your position with conviction." },
  { name: "Eight of Wands", arcana: "Wands", interpretation: "Everything accelerates. Rapid movement and swift communication are the themes — be ready to act quickly." },
  { name: "Nine of Wands", arcana: "Wands", interpretation: "You're nearly there, but fatigue is real. One last push of resilience will carry you through to the finish line." },
  { name: "Ten of Wands", arcana: "Wands", interpretation: "You're carrying too much. Delegate, simplify, and release burdens that are no longer yours to shoulder alone." },
  { name: "Page of Wands", arcana: "Wands", interpretation: "An enthusiastic messenger or new creative idea arrives. Explore with curiosity and youthful daring." },
  { name: "Knight of Wands", arcana: "Wands", interpretation: "Bold, impulsive energy charges forward. Act on passion — but don't let recklessness burn the bridge." },
  { name: "Queen of Wands", arcana: "Wands", interpretation: "Confidence and charisma lead the way. Stand in your power with warmth, and others will naturally follow." },
  { name: "King of Wands", arcana: "Wands", interpretation: "Visionary leadership calls. Take command of your creative vision with boldness and inspire others through action." },

  // --- Minor Arcana: Cups ---
  { name: "Ace of Cups", arcana: "Cups", interpretation: "Emotional renewal and love overflow. Open your heart — a new relationship or creative surge is beginning." },
  { name: "Two of Cups", arcana: "Cups", interpretation: "Partnership and mutual attraction flourish. A meaningful connection deepens through shared understanding." },
  { name: "Three of Cups", arcana: "Cups", interpretation: "Celebration with community. Friendships, milestones, and joyful gatherings lift your spirit." },
  { name: "Four of Cups", arcana: "Cups", interpretation: "Apathy and withdrawal set in. Look up — an opportunity you haven't noticed may be right in front of you." },
  { name: "Five of Cups", arcana: "Cups", interpretation: "Grief over what was lost. Acknowledge the pain, but turn toward what still remains — not all is gone." },
  { name: "Six of Cups", arcana: "Cups", interpretation: "Nostalgia and innocence resurface. Reconnecting with the past — or a childhood joy — brings comfort and clarity." },
  { name: "Seven of Cups", arcana: "Cups", interpretation: "Fantasy and illusion abound. So many choices, but not all are real — ground yourself before deciding." },
  { name: "Eight of Cups", arcana: "Cups", interpretation: "Walk away from what no longer fulfills you. It takes courage to leave, but your deeper self calls you onward." },
  { name: "Nine of Cups", arcana: "Cups", interpretation: "The wish card. Contentment and satisfaction are yours — enjoy this moment of emotional fulfillment." },
  { name: "Ten of Cups", arcana: "Cups", interpretation: "Lasting happiness and family harmony. A dream of home, love, and belonging has been realized." },
  { name: "Page of Cups", arcana: "Cups", interpretation: "Tender, intuitive energy arrives. A dreamy message or unexpected emotional insight invites you to listen." },
  { name: "Knight of Cups", arcana: "Cups", interpretation: "A romantic or creative quest is underway. Follow your heart — charm and imagination open the way." },
  { name: "Queen of Cups", arcana: "Cups", interpretation: "Lead with emotional intelligence and compassion. Nurture others while staying attuned to your own inner wisdom." },
  { name: "King of Cups", arcana: "Cups", interpretation: "Master of emotional balance. Navigate feelings with wisdom and restraint — your calm is your greatest strength." },

  // --- Minor Arcana: Swords ---
  { name: "Ace of Swords", arcana: "Swords", interpretation: "A breakthrough of clarity cuts through confusion. Truth and intellectual power surge — speak it plainly." },
  { name: "Two of Swords", arcana: "Swords", interpretation: "You're stuck at a crossroads, avoiding a hard decision. Remove the blindfold and face what you already know." },
  { name: "Three of Swords", arcana: "Swords", interpretation: "Heartbreak and painful truth arrive. Allow yourself to grieve — healing can only begin when the wound is acknowledged." },
  { name: "Four of Swords", arcana: "Swords", interpretation: "Rest and recuperation are essential right now. Withdraw from the battlefield to restore your mental energy." },
  { name: "Five of Swords", arcana: "Swords", interpretation: "A hollow victory or conflict with a high cost. Ask whether winning this battle is worth the relationship or peace lost." },
  { name: "Six of Swords", arcana: "Swords", interpretation: "Moving on from turbulence toward calmer waters. Transition isn't painless, but the direction is right." },
  { name: "Seven of Swords", arcana: "Swords", interpretation: "Deception or strategy in the air — yours or someone else's. Act tactfully, but watch for hidden motives." },
  { name: "Eight of Swords", arcana: "Swords", interpretation: "You feel trapped, but the restriction is largely mental. Remove the blindfold — you have more freedom than you think." },
  { name: "Nine of Swords", arcana: "Swords", interpretation: "Anxiety and sleepless worry dominate the mind. The nightmares may be worse than reality — seek support." },
  { name: "Ten of Swords", arcana: "Swords", interpretation: "A painful ending reaches its lowest point. But with this rock-bottom moment, the only way forward is up." },
  { name: "Page of Swords", arcana: "Swords", interpretation: "Sharp curiosity and a hunger for truth. Stay alert — new information or a clever idea demands your attention." },
  { name: "Knight of Swords", arcana: "Swords", interpretation: "Charging forward with fierce conviction. Brilliant but headstrong — slow down enough to think before striking." },
  { name: "Queen of Swords", arcana: "Swords", interpretation: "Clear-eyed, direct, and fiercely independent. Cut through sentiment to see the truth — then speak it with grace." },
  { name: "King of Swords", arcana: "Swords", interpretation: "Intellectual authority and impartial judgment. Make decisions from logic and principle, not emotion or bias." },

  // --- Minor Arcana: Pentacles ---
  { name: "Ace of Pentacles", arcana: "Pentacles", interpretation: "A new material opportunity seeds itself. Plant it carefully — this is the foundation of something lasting and real." },
  { name: "Two of Pentacles", arcana: "Pentacles", interpretation: "Juggling multiple demands with agile grace. Flexibility is your strength — but keep an eye on what you're balancing." },
  { name: "Three of Pentacles", arcana: "Pentacles", interpretation: "Collaboration and craftsmanship excel together. Combine your skills with others' — teamwork elevates the work." },
  { name: "Four of Pentacles", arcana: "Pentacles", interpretation: "Clinging too tightly to what you have. Security is wise, but hoarding — of money, love, or energy — creates stagnation." },
  { name: "Five of Pentacles", arcana: "Pentacles", interpretation: "Hard times and feelings of scarcity. Help is closer than it seems — don't let pride prevent you from asking." },
  { name: "Six of Pentacles", arcana: "Pentacles", interpretation: "Generosity flows in or out. Whether giving or receiving, ensure the exchange feels fair and dignified." },
  { name: "Seven of Pentacles", arcana: "Pentacles", interpretation: "Pause to assess your progress. You've invested much — reflect honestly on whether the harvest will be worth it." },
  { name: "Eight of Pentacles", arcana: "Pentacles", interpretation: "Diligence and skill-building pay off. Focus on your craft with quiet dedication — mastery is built rep by rep." },
  { name: "Nine of Pentacles", arcana: "Pentacles", interpretation: "Self-sufficiency and refined success. Enjoy the fruits of your independence — you earned this comfort." },
  { name: "Ten of Pentacles", arcana: "Pentacles", interpretation: "Lasting wealth, legacy, and family stability. The seeds you planted create roots that will outlast you." },
  { name: "Page of Pentacles", arcana: "Pentacles", interpretation: "Eager to learn and build. A practical opportunity or studious mindset opens new doors — commit to the process." },
  { name: "Knight of Pentacles", arcana: "Pentacles", interpretation: "Steady, methodical, and reliable. Progress may be slow, but your consistent effort will outlast every shortcut." },
  { name: "Queen of Pentacles", arcana: "Pentacles", interpretation: "Abundance rooted in practicality. Nurture your home, health, and finances with warmth and earthy wisdom." },
  { name: "King of Pentacles", arcana: "Pentacles", interpretation: "Mastery of the material world. Build with confidence — your proven judgment and steady hand create real prosperity." },
];

export function drawRandom() {
  return deck[Math.floor(Math.random() * deck.length)];
}