#version: "3.9"

services:
  app:
    build: .
    container_name: Aurora
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://tarot:tarotpass@postgres:5432/tarotdb
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: tarot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tarot
      POSTGRES_PASSWORD: tarotpass
      POSTGRES_DB: tarotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: